### ISSUE TITLE
support gitlab 

### ISSUE THREAD

**Issue by logicminds** [drwahl/puppet-git-hooks#37]
Since gitlab controls the repo from a ui its not normal practice to add server side hooks since they have tight integration using web hooks instead.  However, they do allow server side hooks if put in a custom_hooks directory inside the repo.  So when installing a hook you would have to change the hooks directory to 'custom_hooks'.

**Comment by drwahl** [comment]
It's been a while since I've actually used these hooks (new job, different configuration management platform).  As you mention, it isn't common to do server-side hooks in gitlab, however, that is exactly what I was doing for about a year.  If I can find some time, I will try to spin up a proof-of-concept/lab with this setup and try the custom_hooks directory and see if i can get these hooks working with that workflow.

**Comment by mrjoshuap** [comment]
I updated the deploy-git-hook script and added a new flag:
```
-g                      enable to install in Git Lab repo custom_hooks
```
Install will be the same, except instead of creating links  in ```repo.git/hooks``` it will install into ```repo.git/custom_hooks``` as documented in http://doc.gitlab.com/ce/hooks/custom_hooks.html
