### ISSUE TITLE
pre-receive hook doesn't work correctly with new branches

### ISSUE THREAD

**Issue by divansantana** [drwahl/puppet-git-hooks#60]
As far as I can see, it seems that the pre-receive hook isn't working correctly when one creates a new branch and pushes it.

Specifically:

1. clone repo
2. Create new branch `test_branch` from master
3. Make change in new branch and commit it.
4. Push the new branch to the remote git server via 
```
git push origin test_branch:test_branch
```

Expected:
5. Git remote server runs pre-receive hook, runs the tests on the new changes file and reports an error if there is one.

Actual:
5. It's reporting:
a)
```
cannot handle more than 25 refs
```
On each and every branch that exists, not just the `test_branch`
b) It's doing a test on each and every file in the repo, not just the recent file that changed.

**Comment by divansantana** [comment]
In case it matters, I installed this on a gitlab server.
I installed it via something like this:
```
cd /opt
git clone https://github.com/drwahl/puppet-git-hooks.git
cd /var/opt/gitlab/git-data/repositories/F3333000/puppet-main.git
mkdir custom_hooks
ln -s /var/opt/gitlab/git-data/repositories/F3333000/puppet-main.git/custom_hooks/pre-receive /opt/puppet-git-hooks/pre-receive
```

**Comment by jharlow1** [comment]
I am having similar issues in gitlab. It appears that for a new branch, it's getting strange values for newrev and oldrev.

If I do:

git clone git@mygitlabserver.example.com:puppet/myrepo.git
git checkout -b testbranch1
<make a change, add it and commit>
git push origin testbranch

git checkout master
git checkout -b testbranch2
<make a change, add it and commit>
git push origin testbranch2

And have some debug logging enabled in the pre-receive hook, For the second push I see that it gets newrev = master and oldrev = testbranch1.  So it's doing a diff between master (thinking this is what I just pushed), and testbranch1 (thinking that's the parent branch), instead of a diff between testbranch2 and master.

I'm working on figuring out why this is the case. If I figure it out I'll create a PR

**Comment by drwahl** [comment]
Thanks, @jharlow1. I'm not using puppet much these days, so a PR is the best way to get this fixed.

**Comment by divansantana** [comment]
thanks @jharlow1 . I was just looking at this briefly today. Was hoping to have time to debug and work on a patch soon. Works been a bit crazy lately so hopefully it settles down soon and I might have a chance to attempt a fix too.

**Comment by divansantana** [comment]
@jharlow1 any chance on having a look at this? We're not quite sure how to fix this... :(
Or pointers on how to debug and work to close this.

**Comment by divansantana** [comment]
Ok I've debugged this a bit.
Can confirm what @jharlow1 said above.

There are a couple of gitlab issues that are due to be fixed and released shortly which I *think* might help. Check them out and let me know what you think.
https://gitlab.com/gitlab-org/gitlab-ee/issues/279
https://gitlab.com/gitlab-org/gitlab-ee/issues/428
https://gitlab.com/gitlab-org/gitlab-ee/issues/429

**Comment by divansantana** [comment]
We should check this again with GitLab 8.7 release 22 April.

**Comment by jharlow1** [comment]
Apologies for lack of an update...I got pulled off onto higher priority projects and hadn't had a chance to get deeper into this yet. Thanks @divansantana for doing some more digging and posting your findings. 279 and 428 do look promising. It looks like both of those should be fixed by 8.6.3 which appears to be imminent.

Once that's released, I'll try and get our server updated and see if the problem magically disappears.

**Comment by jharlow1** [comment]
Still seems to be an issue with the latest gitlab (8.6.4)....going to try and take another look at this next week.

**Comment by jharlow1** [comment]
After digging in, I don't think this was gitlab specific. I think the new branch logic was just off, as far as I could tell.

**Comment by divansantana** [comment]
@jharlow1 wahoo. This seems to work just great. Thanks a ton.

**Comment by divansantana** [comment]
@jharlow1 ok so this does fix this bug.
However this [bug](https://gitlab.com/gitlab-org/gitlab-ce/issues/1458) in gitlab effected some of our users to I had to apply that patch.

I now have another issue, where users can push there branch with this hook enabled, however we can't merge the branch pushed (which passed checks) on the gitlab frontend to our main target branch.

gitlab-ctl tail reports
```
==> /var/log/gitlab/gitlab-rails/production.log <==
Git operation was rejected by pre-receive hook
```

This might be an issue in the hook still?
Can you merge branches pushed with the hook enabled?

**Comment by divansantana** [comment]
Ok this could be due to another gitlab issue :disappointed:  https://gitlab.com/gitlab-org/gitlab-ce/issues/13473

**Comment by divansantana** [comment]
@jharlow1 oh lol, you created that issue. ok. It seems https://gitlab.com/gitlab-org/gitlab-ce/issues/13473 and https://gitlab.com/gitlab-org/gitlab-ce/issues/4152 are the reason for the issue above where I can't merge via frontend. It's a gitlab issue AFAIK that requires the pre-receive hook to do this:
```
unset BUNDLE_GEMFILE RUBYLIB RUBYOPT GEM_HOME
```
Then all works.

**Comment by jharlow1** [comment]
@divansantana  - Thanks for the workaround on that gitlab issue. That seems to have solved my remaining issues there as well!
